<?php

namespace Flowcode\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockRepository extends EntityRepository
{
    public function findBlockByPageAndLangAndInType($page_id, $lang, $type)
    {
        $qb = $this->createQueryBuilder("b");
        $qb->where("b.page = :pageId")->setParameter("pageId", $page_id);
        $qb->andWhere("b.lang = :lang")->setParameter("lang", $lang);
        $qb->andWhere("b.type in (:types)")->setParameter("types", $type);
        return $qb->getQuery()->getResult();
    }
}
