<?php

namespace Flowcode\PageBundle\Repository;

/**
 * MenuItemLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuItemLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
