<?php

namespace Flowcode\PageBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{

    public function findByCategory($categoryId, $exceptPageId = null)
    {
        $qb = $this->createQueryBuilder("p");
        $qb->where("p.enabled = 1");


        $qb->andWhere("p.category = :category_id")
            ->setParameter("category_id", $categoryId);

        if ($exceptPageId) {
            $qb->andWhere("p.id <> :except_id")
                ->setParameter("except_id", $exceptPageId);
        }

        $qb->orderBy("p.position", "ASC");

        return $qb->getQuery()->getResult();
    }

    public function getMostViewed($length = 3)
    {
        $qb = $this->createQueryBuilder("p");
        $qb->orderBy("p.viewCount", "DESC");
        $qb->setMaxResults($length);
        return $qb->getQuery()->getResult();
    }

    public function getTotalViewedCount()
    {
        $qb = $this->createQueryBuilder("p");
        $qb->select("SUM(p.viewCount)");
        return $qb->getQuery()->getSingleScalarResult();
    }
}
