services:

    amulen.page.form.page:
        class: Flowcode\PageBundle\Form\PageType
        arguments: [%flowcode_page.templates%]
        tags:
            - { name: form.type, alias: page_type }

    amulen.page.form.block:
        class: Flowcode\PageBundle\Form\BlockType
        tags:
            - { name: form.type, alias: block_type }

    amulen.page.form.menuitemlabel:
        class: Flowcode\PageBundle\Form\MenuItemLabelType
        tags:
            - { name: form.type, alias: menuitemlabel_type }

    amulen.page.form.htmlblock:
        class: Flowcode\PageBundle\Form\HtmlBlockType
        tags:
            - { name: form.type, alias: htmlblock_type }

    amulen.page.form.textblock:
        class: Flowcode\PageBundle\Form\TextBlockType
        tags:
            - { name: form.type, alias: textblock_type }

    amulen.page.locale_listener:
        class: Flowcode\PageBundle\Listener\LocaleListener
        arguments: [%kernel.default_locale%]
        tags:
            -  { name: kernel.event_subscriber }

    amulen.page.repository.menuitem:
        class: Doctrine\ORM\EntityRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments:
            - Amulen\PageBundle\Entity\MenuItem

    amulen.page.repository.block:
        class: Doctrine\ORM\EntityRepository
        factory: [@doctrine.orm.entity_manager, getRepository]
        arguments:
            - Amulen\PageBundle\Entity\Block

    amulen.page.service.menu:
        class: Flowcode\PageBundle\Services\MenuService
        arguments: ['@amulen.page.repository.menuitem']

    amulen.page.service.page:
        class: Flowcode\PageBundle\Services\PageService
        arguments: ['@service_container', '@amulen.page.repository.block']

    amulen.page.showmenu_eventsubscriber:
        class: Flowcode\PageBundle\Event\ShowMenuSubscriber
        arguments: ['@router', '@translator']
        tags:
            - { name: kernel.event_subscriber }